// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EsbuildpubApp: typeof import('dubhe-esbuildpub/app')['default']
    ViteoutApp: typeof import('dubhe-viteout/app')['default']
    ViteoutHello: typeof import('dubhe-viteout/hello')['default']
  }
}
