// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppApp: typeof import('!app/app')['default']
    AppHello: typeof import('!app/hello')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RAppHello: typeof import('!app/hello')['default']
    Share: typeof import('./src/components/Share.vue')['default']
  }
}
